theme = "hugo_theme_pickles"
baseurl = "https://blog.manninglabs.com"
languageCode = "en-us"
Title = "The Manning Labs Blog"

copyright = "&copy; Copyright 2017 Manning Labs LLC"

[params]
  paginate = 10
  ga_api_key = "UA-110200814-2"
  author = ""
  authorwebsite = ""
  avatar = ""
  contact = ""
  bio = ""

  subtitle = ""

  logo = "https://www.manninglabs.com/assets/manning-labs-logo%402x.png"
  favicon = ""


